name = "habitica-companion"
compatibility_date = "2026-05-13"
pages_build_output_dir = "output/wwwroot"

[[kv_namespaces]]
binding = "HABITICA_SYNC_KV"
id = "habitica-companion-sync"
preview_id = "habitica-companion-sync"

[[d1_databases]]
binding = "HABITICA_PARTY_DB"
database_name = "habitica-companion-party-sync"
database_id = "habitica-companion-party-sync"
preview_database_id = "habitica-companion-party-sync"
