<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Habitica.Api\Habitica.Api.csproj" />
    <ProjectReference Include="..\Habitica.Domain\Habitica.Domain.csproj" />
    <ProjectReference Include="..\Habitica.Rules\Habitica.Rules.csproj" />
    <ProjectReference Include="..\Habitica.Storage\Habitica.Storage.csproj" />
  </ItemGroup>

</Project>
