using System.Text.RegularExpressions;

namespace Habitica.WebApp.Theme;

public static partial class ColorSchemeCatalog
{
    public const string AlphaId = "alpha";

    public static IReadOnlyList<ColorSchemeDefinition> BuiltInSchemes { get; } = new[]
    {
        new ColorSchemeDefinition(
            AlphaId,
            "Alpha (Light)",
            true,
            new ColorSchemeTokens(
                "#f5efe2",
                "rgba(255, 250, 241, 0.92)",
                "rgba(23, 63, 59, 0.12)",
                "#162423",
                "#5f6d67",
                "#2d746e",
                "#c5772b",
                "#a13f35",
                "#2d746e",
                "#43a397",
                "0 24px 60px rgba(22, 36, 35, 0.12)",
                "rgba(255, 255, 255, 0.72)",
                "rgba(255, 250, 241, 0.94)",
                "#2d746e",
                "#c5772b",
                "#d6e7e1",
                "#eaf3ee",
                "#f8fcfa",
                "#173f3b",
                "#f5efe2",
                "#163431",
                "#f5efe2",
                "#ffffff",
                "rgba(22, 36, 35, 0.08)",
                "rgba(95, 109, 103, 0.58)",
                "rgba(95, 109, 103, 0.28)",
                "rgba(255, 255, 255, 0.9)",
                "rgba(22, 36, 35, 0.12)")),
        new ColorSchemeDefinition(
            "habitica",
            "Habitica (Light)",
            true,
            new ColorSchemeTokens(
                "#f7f4ff",
                "rgba(255, 255, 255, 0.94)",
                "rgba(79, 42, 147, 0.16)",
                "#24113f",
                "#6f6384",
                "#6133b4",
                "#ffbe5d",
                "#de3f5f",
                "#24cc8f",
                "#2995cd",
                "0 24px 60px rgba(44, 24, 82, 0.14)",
                "rgba(255, 255, 255, 0.78)",
                "rgba(255, 255, 255, 0.96)",
                "#6133b4",
                "#2995cd",
                "#ded3fa",
                "#eee8ff",
                "#faf7ff",
                "#4f2a93",
                "#fff7ff",
                "#2f1d52",
                "#fff7ff",
                "#ffffff",
                "rgba(79, 42, 147, 0.08)",
                "rgba(111, 99, 132, 0.62)",
                "rgba(111, 99, 132, 0.28)",
                "rgba(255, 255, 255, 0.94)",
                "rgba(79, 42, 147, 0.16)")),
        new ColorSchemeDefinition(
            "gryphy-light",
            "Gryphy (Light)",
            true,
            new ColorSchemeTokens(
                "#f7f1ff",
                "rgba(255, 252, 255, 0.94)",
                "rgba(103, 49, 184, 0.16)",
                "#201136",
                "#6a5c77",
                "#7b2dd6",
                "#f0a400",
                "#d94768",
                "#1f9f7a",
                "#3197e5",
                "0 24px 60px rgba(32, 17, 54, 0.14)",
                "rgba(255, 255, 255, 0.78)",
                "rgba(255, 252, 255, 0.96)",
                "#7b2dd6",
                "#3197e5",
                "#dfd1f8",
                "#eee6ff",
                "#fbf8ff",
                "#4f2380",
                "#fff7ff",
                "#2d1945",
                "#fff7ff",
                "#ffffff",
                "rgba(103, 49, 184, 0.08)",
                "rgba(106, 92, 119, 0.62)",
                "rgba(106, 92, 119, 0.28)",
                "rgba(255, 252, 255, 0.94)",
                "rgba(103, 49, 184, 0.16)")),
        new ColorSchemeDefinition(
            "gryphy-dark",
            "Gryphy (Dark)",
            true,
            new ColorSchemeTokens(
                "#12081f",
                "rgba(31, 15, 50, 0.94)",
                "rgba(178, 93, 255, 0.22)",
                "#fff7ff",
                "#c8b9d8",
                "#b25dff",
                "#ffcf26",
                "#ff6f8f",
                "#62d6bd",
                "#58b9ff",
                "0 24px 60px rgba(0, 0, 0, 0.36)",
                "rgba(50, 24, 80, 0.78)",
                "rgba(42, 20, 70, 0.96)",
                "#b25dff",
                "#58b9ff",
                "#241633",
                "#321f49",
                "#452b63",
                "#241336",
                "#fff7ff",
                "#1d102b",
                "#fff7ff",
                "#12081f",
                "rgba(202, 140, 255, 0.1)",
                "rgba(205, 189, 224, 0.54)",
                "rgba(202, 140, 255, 0.26)",
                "#21122f",
                "rgba(202, 140, 255, 0.3)")),
        new ColorSchemeDefinition(
            "midnight-tavern",
            "Midnight Tavern (Dark)",
            true,
            new ColorSchemeTokens(
                "#0d1117",
                "rgba(20, 27, 39, 0.94)",
                "rgba(107, 211, 210, 0.2)",
                "#f5f1e8",
                "#a9b7bd",
                "#6bd3d2",
                "#f2b84b",
                "#ff6b6b",
                "#79d38a",
                "#8bd3ff",
                "0 24px 60px rgba(0, 0, 0, 0.42)",
                "rgba(25, 34, 48, 0.82)",
                "rgba(31, 42, 59, 0.96)",
                "#6bd3d2",
                "#f2b84b",
                "#102326",
                "#173337",
                "#22484d",
                "#111c26",
                "#f5f1e8",
                "#091016",
                "#f5f1e8",
                "#091016",
                "rgba(245, 241, 232, 0.1)",
                "rgba(169, 183, 189, 0.58)",
                "rgba(107, 211, 210, 0.24)",
                "#172231",
                "rgba(107, 211, 210, 0.32)")),
        new ColorSchemeDefinition(
            "dragonfire-keep",
            "Dragonfire Keep (Dark)",
            true,
            new ColorSchemeTokens(
                "#160b08",
                "rgba(42, 20, 14, 0.94)",
                "rgba(255, 126, 53, 0.24)",
                "#fff1df",
                "#d9bca9",
                "#ff7e35",
                "#ffd166",
                "#ff4d5f",
                "#70d68c",
                "#ff9f6e",
                "0 24px 60px rgba(0, 0, 0, 0.44)",
                "rgba(58, 27, 18, 0.78)",
                "rgba(69, 31, 20, 0.96)",
                "#ff7e35",
                "#ffd166",
                "#32170f",
                "#452015",
                "#5c2c1d",
                "#44190f",
                "#fff1df",
                "#2a0f0a",
                "#fff1df",
                "#160b08",
                "rgba(255, 241, 223, 0.1)",
                "rgba(217, 188, 169, 0.56)",
                "rgba(255, 126, 53, 0.28)",
                "#32170f",
                "rgba(255, 126, 53, 0.34)")),
        new ColorSchemeDefinition(
            "neon-rogue",
            "Neon Rogue (Dark)",
            true,
            new ColorSchemeTokens(
                "#09071a",
                "rgba(18, 14, 43, 0.94)",
                "rgba(0, 231, 255, 0.24)",
                "#f7f7ff",
                "#bbb7df",
                "#00e7ff",
                "#ff3df2",
                "#ff4f7a",
                "#40f29a",
                "#9b7cff",
                "0 24px 60px rgba(0, 0, 0, 0.48)",
                "rgba(24, 19, 58, 0.82)",
                "rgba(31, 24, 75, 0.96)",
                "#00e7ff",
                "#ff3df2",
                "#092a33",
                "#0d3d49",
                "#125766",
                "#120d35",
                "#f7f7ff",
                "#0b0825",
                "#f7f7ff",
                "#09071a",
                "rgba(247, 247, 255, 0.1)",
                "rgba(187, 183, 223, 0.54)",
                "rgba(0, 231, 255, 0.3)",
                "#18133a",
                "rgba(0, 231, 255, 0.34)")),
        new ColorSchemeDefinition(
            "frost-healer",
            "Frost Healer (Light)",
            true,
            new ColorSchemeTokens(
                "#eef9ff",
                "rgba(255, 255, 255, 0.94)",
                "rgba(34, 124, 157, 0.16)",
                "#15313d",
                "#607986",
                "#227c9d",
                "#7d5fff",
                "#c84a68",
                "#1f9d7a",
                "#5bbfe8",
                "0 24px 60px rgba(21, 49, 61, 0.12)",
                "rgba(255, 255, 255, 0.78)",
                "rgba(248, 253, 255, 0.96)",
                "#227c9d",
                "#7d5fff",
                "#ccebf5",
                "#e5f6fb",
                "#f8fdff",
                "#19556d",
                "#f4fbff",
                "#164255",
                "#f4fbff",
                "#ffffff",
                "rgba(21, 49, 61, 0.08)",
                "rgba(96, 121, 134, 0.6)",
                "rgba(34, 124, 157, 0.24)",
                "rgba(255, 255, 255, 0.92)",
                "rgba(34, 124, 157, 0.16)")),
        new ColorSchemeDefinition(
            "sunlit-stable",
            "Sunlit Stable (Light)",
            true,
            new ColorSchemeTokens(
                "#fff6dc",
                "rgba(255, 253, 246, 0.94)",
                "rgba(151, 91, 38, 0.16)",
                "#312315",
                "#756756",
                "#2f8a7b",
                "#e39a2d",
                "#b64f44",
                "#3f9b62",
                "#63b6a6",
                "0 24px 60px rgba(49, 35, 21, 0.12)",
                "rgba(255, 255, 255, 0.72)",
                "rgba(255, 253, 246, 0.96)",
                "#2f8a7b",
                "#e39a2d",
                "#cde8df",
                "#e5f4ef",
                "#f8fcfa",
                "#286256",
                "#fff8e8",
                "#24483f",
                "#fff8e8",
                "#ffffff",
                "rgba(49, 35, 21, 0.08)",
                "rgba(117, 103, 86, 0.58)",
                "rgba(151, 91, 38, 0.24)",
                "rgba(255, 255, 255, 0.9)",
                "rgba(151, 91, 38, 0.16)")),
        new ColorSchemeDefinition(
            "mosswood-quest",
            "Mosswood Quest (Light)",
            true,
            new ColorSchemeTokens(
                "#edf2df",
                "rgba(252, 255, 244, 0.94)",
                "rgba(72, 106, 58, 0.18)",
                "#1f2d1d",
                "#66725e",
                "#4f8a46",
                "#a8702c",
                "#a9473f",
                "#3c8f68",
                "#78a85c",
                "0 24px 60px rgba(31, 45, 29, 0.12)",
                "rgba(255, 255, 255, 0.68)",
                "rgba(252, 255, 244, 0.96)",
                "#4f8a46",
                "#a8702c",
                "#d3e5cc",
                "#e9f2e4",
                "#f8fcf6",
                "#365d31",
                "#f7ffef",
                "#2d482b",
                "#f7ffef",
                "#ffffff",
                "rgba(31, 45, 29, 0.08)",
                "rgba(102, 114, 94, 0.58)",
                "rgba(72, 106, 58, 0.25)",
                "rgba(255, 255, 255, 0.88)",
                "rgba(72, 106, 58, 0.16)")),
        new ColorSchemeDefinition(
            "potion-shop",
            "Potion Shop (Light)",
            true,
            new ColorSchemeTokens(
                "#f6edff",
                "rgba(255, 250, 255, 0.94)",
                "rgba(136, 78, 191, 0.18)",
                "#261238",
                "#706079",
                "#8b3fd1",
                "#27a7a3",
                "#cf4772",
                "#2faf72",
                "#c267e8",
                "0 24px 60px rgba(38, 18, 56, 0.14)",
                "rgba(255, 255, 255, 0.74)",
                "rgba(255, 250, 255, 0.96)",
                "#8b3fd1",
                "#27a7a3",
                "#ded1f0",
                "#efe7fa",
                "#fbf8ff",
                "#5b2b83",
                "#fff7ff",
                "#3b2152",
                "#fff7ff",
                "#ffffff",
                "rgba(38, 18, 56, 0.08)",
                "rgba(112, 96, 121, 0.58)",
                "rgba(136, 78, 191, 0.26)",
                "rgba(255, 255, 255, 0.92)",
                "rgba(136, 78, 191, 0.18)")),
        new ColorSchemeDefinition(
            "boss-battle",
            "Boss Battle (Dark)",
            true,
            new ColorSchemeTokens(
                "#171414",
                "rgba(35, 31, 31, 0.94)",
                "rgba(235, 78, 85, 0.24)",
                "#fff0e8",
                "#c9b7ad",
                "#eb4e55",
                "#f0b64f",
                "#ff6b6b",
                "#78d085",
                "#ff8a75",
                "0 24px 60px rgba(0, 0, 0, 0.44)",
                "rgba(45, 39, 39, 0.82)",
                "rgba(55, 47, 47, 0.96)",
                "#eb4e55",
                "#f0b64f",
                "#351b1d",
                "#4a2428",
                "#633137",
                "#421f22",
                "#fff0e8",
                "#241616",
                "#fff0e8",
                "#171414",
                "rgba(255, 240, 232, 0.1)",
                "rgba(201, 183, 173, 0.56)",
                "rgba(235, 78, 85, 0.28)",
                "#2a2424",
                "rgba(235, 78, 85, 0.32)")),
        new ColorSchemeDefinition(
            "quiet-ledger",
            "Quiet Ledger (Light)",
            true,
            new ColorSchemeTokens(
                "#eef0ea",
                "rgba(250, 250, 246, 0.94)",
                "rgba(85, 96, 91, 0.16)",
                "#202624",
                "#66706c",
                "#536b63",
                "#8a7354",
                "#9d5550",
                "#557a61",
                "#7b8f89",
                "0 24px 60px rgba(32, 38, 36, 0.1)",
                "rgba(255, 255, 255, 0.68)",
                "rgba(250, 250, 246, 0.96)",
                "#536b63",
                "#8a7354",
                "#d9e0d8",
                "#e9ede8",
                "#f8faf7",
                "#3f554e",
                "#f7f8f4",
                "#35443f",
                "#f7f8f4",
                "#ffffff",
                "rgba(32, 38, 36, 0.08)",
                "rgba(102, 112, 108, 0.58)",
                "rgba(85, 96, 91, 0.24)",
                "rgba(255, 255, 255, 0.88)",
                "rgba(85, 96, 91, 0.16)")),
        new ColorSchemeDefinition(
            "celestial-inn",
            "Celestial Inn (Dark)",
            true,
            new ColorSchemeTokens(
                "#121c33",
                "rgba(25, 38, 67, 0.94)",
                "rgba(116, 161, 255, 0.22)",
                "#f3f7ff",
                "#bbc7df",
                "#74a1ff",
                "#e8c46a",
                "#ff6f8f",
                "#76d6aa",
                "#b38cff",
                "0 24px 60px rgba(0, 0, 0, 0.38)",
                "rgba(31, 48, 84, 0.8)",
                "rgba(36, 55, 96, 0.96)",
                "#74a1ff",
                "#e8c46a",
                "#1a2d54",
                "#263f73",
                "#345491",
                "#1a2d54",
                "#f3f7ff",
                "#101a31",
                "#f3f7ff",
                "#121c33",
                "rgba(243, 247, 255, 0.1)",
                "rgba(187, 199, 223, 0.56)",
                "rgba(116, 161, 255, 0.28)",
                "#1b2c50",
                "rgba(116, 161, 255, 0.32)")),
        new ColorSchemeDefinition(
            "mana-mirage",
            "Mana Mirage (Dark)",
            true,
            new ColorSchemeTokens(
                "#14001f",
                "rgba(38, 0, 63, 0.94)",
                "rgba(255, 52, 246, 0.28)",
                "#fff4ff",
                "#e5b8ff",
                "#00ffcc",
                "#ff34f6",
                "#ff3366",
                "#b8ff2c",
                "#ffe600",
                "0 24px 60px rgba(0, 0, 0, 0.52)",
                "rgba(43, 0, 69, 0.82)",
                "rgba(57, 0, 95, 0.96)",
                "#00ffcc",
                "#ff34f6",
                "#2a003f",
                "#410061",
                "#5e008a",
                "#25003d",
                "#fff4ff",
                "#090012",
                "#fff4ff",
                "#14001f",
                "rgba(255, 244, 255, 0.1)",
                "rgba(229, 184, 255, 0.56)",
                "rgba(255, 52, 246, 0.3)",
                "#26003f",
                "rgba(0, 255, 204, 0.34)")),
        new ColorSchemeDefinition(
            "mushroom-meadow",
            "Mushroom Meadow (Light)",
            true,
            new ColorSchemeTokens(
                "#fdf0ff",
                "rgba(255, 248, 255, 0.92)",
                "rgba(200, 0, 200, 0.18)",
                "#2a0a3d",
                "#7a5a8a",
                "#c800c8",
                "#00d97e",
                "#ff2e63",
                "#2faf72",
                "#ff8a00",
                "0 24px 60px rgba(120, 0, 120, 0.18)",
                "rgba(255, 255, 255, 0.74)",
                "rgba(255, 248, 255, 0.96)",
                "#c800c8",
                "#00d97e",
                "#e9b3f5",
                "#f3d6fb",
                "#fbf0ff",
                "#6a0080",
                "#fff0ff",
                "#2a0a3d",
                "#fff0ff",
                "#ffffff",
                "rgba(120, 0, 120, 0.08)",
                "rgba(122, 90, 138, 0.58)",
                "rgba(200, 0, 200, 0.26)",
                "rgba(255, 255, 255, 0.92)",
                "rgba(200, 0, 200, 0.18)")),
        new ColorSchemeDefinition(
            "mushroom-trip",
            "Mushroom Trip (Dark)",
            true,
            new ColorSchemeTokens(
                "#0a0014",
                "rgba(30, 0, 50, 0.94)",
                "rgba(255, 0, 200, 0.28)",
                "#f5e8ff",
                "#c89aff",
                "#ff00cc",
                "#00ffaa",
                "#ff2e63",
                "#7bff3d",
                "#ffe600",
                "0 24px 60px rgba(0, 0, 0, 0.52)",
                "rgba(40, 0, 65, 0.82)",
                "rgba(52, 0, 85, 0.96)",
                "#ff00cc",
                "#00ffaa",
                "#2a0040",
                "#3d005c",
                "#56007e",
                "#1a0028",
                "#f5e8ff",
                "#12001f",
                "#f5e8ff",
                "#0a0014",
                "rgba(245, 232, 255, 0.1)",
                "rgba(200, 154, 255, 0.56)",
                "rgba(255, 0, 200, 0.3)",
                "#20002f",
                "rgba(255, 0, 200, 0.34)")),
        new ColorSchemeDefinition(
            "frosted-cake",
            "Frosted Cake (Light)",
            true,
            new ColorSchemeTokens(
                "#fff0f6",
                "rgba(255, 250, 253, 0.92)",
                "rgba(255, 20, 147, 0.2)",
                "#3d0a2a",
                "#9a6a82",
                "#ff1493",
                "#00cfff",
                "#ff3b3b",
                "#19c37d",
                "#ffb300",
                "0 24px 60px rgba(180, 0, 90, 0.16)",
                "rgba(255, 255, 255, 0.74)",
                "rgba(255, 250, 253, 0.96)",
                "#ff1493",
                "#00cfff",
                "#ffc1dd",
                "#ffd9e8",
                "#fff0f6",
                "#ff1493",
                "#fff0f6",
                "#3d0a2a",
                "#fff0f6",
                "#ffffff",
                "rgba(180, 0, 90, 0.08)",
                "rgba(154, 106, 130, 0.58)",
                "rgba(255, 20, 147, 0.26)",
                "rgba(255, 255, 255, 0.92)",
                "rgba(255, 20, 147, 0.2)")),
        new ColorSchemeDefinition(
            "sugar-crash",
            "Sugar Crash (Dark)",
            true,
            new ColorSchemeTokens(
                "#0c0010",
                "rgba(28, 0, 36, 0.94)",
                "rgba(255, 222, 0, 0.26)",
                "#fff6e8",
                "#ffb3d9",
                "#ffde00",
                "#ff3df2",
                "#ff2e4f",
                "#39ff88",
                "#00e7ff",
                "0 24px 60px rgba(0, 0, 0, 0.55)",
                "rgba(40, 0, 52, 0.82)",
                "rgba(54, 0, 70, 0.96)",
                "#ffde00",
                "#ff3df2",
                "#2a0036",
                "#3d004f",
                "#56006e",
                "#1a0022",
                "#fff6e8",
                "#12001a",
                "#fff6e8",
                "#0c0010",
                "rgba(255, 246, 232, 0.1)",
                "rgba(255, 179, 217, 0.56)",
                "rgba(255, 222, 0, 0.3)",
                "#1e0026",
                "rgba(255, 222, 0, 0.34)"))
    };

    public static IReadOnlyList<ColorSchemeTokenDescriptor> EditableTokens { get; } = new[]
    {
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.Background), "Background"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.CardBackground), "Card background"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.CardBorder), "Card border"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.Ink), "Text"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.Muted), "Muted text"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.Primary), "Primary"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.Accent), "Accent"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.Danger), "Danger"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.Success), "Success"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.Focus), "Focus"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.Shadow), "Shadow"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.Surface), "Surface"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.SurfaceStrong), "Strong surface"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.ChartPrimary), "Chart primary"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.ChartSecondary), "Chart secondary"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.TaskNegative), "Task min"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.TaskNeutral), "Task base"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.TaskPositive), "Task max"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.AppBarBackground), "Header background"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.AppBarText), "Header text"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.DrawerBackground), "Navigation background"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.DrawerText), "Navigation text"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.ButtonText), "Filled button text"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.DisabledBackground), "Disabled background"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.DisabledText), "Disabled text"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.DisabledBorder), "Disabled border"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.InputBackground), "Input background"),
        new ColorSchemeTokenDescriptor(nameof(ColorSchemeTokens.InputBorder), "Input border")
    };

    public static ColorSchemeDefinition Alpha => BuiltInSchemes[0];

    public static ColorSchemeDefinition Resolve(string? schemeId, IReadOnlyList<ColorSchemeDefinition> customSchemes)
    {
        return BuiltInSchemes.Concat(customSchemes)
            .Select(Complete)
            .FirstOrDefault(scheme => string.Equals(scheme.Id, schemeId, StringComparison.Ordinal))
            ?? Alpha;
    }

    public static ColorSchemeDefinition CreateCustomCopy(ColorSchemeDefinition source, string name)
    {
        return new ColorSchemeDefinition(
            $"custom-{Guid.NewGuid():N}",
            NormalizeName(name, "Custom scheme"),
            false,
            source.Tokens);
    }

    public static string NormalizeName(string? name, string fallback)
    {
        var trimmed = name?.Trim();
        return string.IsNullOrWhiteSpace(trimmed) ? fallback : trimmed.Length > 80 ? trimmed[..80] : trimmed;
    }

    public static bool IsBuiltIn(string? schemeId)
    {
        return BuiltInSchemes.Any(scheme => string.Equals(scheme.Id, schemeId, StringComparison.Ordinal));
    }

    public static bool IsValidTokenValue(string? value)
    {
        if (string.IsNullOrWhiteSpace(value) || value.Length > 120)
        {
            return false;
        }

        return CssColorOrShadowPattern().IsMatch(value.Trim());
    }

    public static ColorSchemeDefinition Complete(ColorSchemeDefinition scheme)
    {
        var fallback = Alpha.Tokens;
        var tokens = scheme.Tokens ?? fallback;
        return scheme with
        {
            Id = string.IsNullOrWhiteSpace(scheme.Id) ? $"custom-{Guid.NewGuid():N}" : scheme.Id,
            Name = NormalizeName(scheme.Name, scheme.IsBuiltIn ? "Alpha" : "Custom scheme"),
            Tokens = new ColorSchemeTokens(
                NormalizeToken(tokens.Background, fallback.Background),
                NormalizeToken(tokens.CardBackground, fallback.CardBackground),
                NormalizeToken(tokens.CardBorder, fallback.CardBorder),
                NormalizeToken(tokens.Ink, fallback.Ink),
                NormalizeToken(tokens.Muted, fallback.Muted),
                NormalizeToken(tokens.Primary, fallback.Primary),
                NormalizeToken(tokens.Accent, fallback.Accent),
                NormalizeToken(tokens.Danger, fallback.Danger),
                NormalizeToken(tokens.Success, fallback.Success),
                NormalizeToken(tokens.Focus, fallback.Focus),
                NormalizeToken(tokens.Shadow, fallback.Shadow),
                NormalizeToken(tokens.Surface, fallback.Surface),
                NormalizeToken(tokens.SurfaceStrong, fallback.SurfaceStrong),
                NormalizeToken(tokens.ChartPrimary, fallback.ChartPrimary),
                NormalizeToken(tokens.ChartSecondary, fallback.ChartSecondary),
                NormalizeToken(tokens.TaskNegative, fallback.TaskNegative),
                NormalizeToken(tokens.TaskNeutral, fallback.TaskNeutral),
                NormalizeToken(tokens.TaskPositive, fallback.TaskPositive),
                NormalizeToken(tokens.AppBarBackground, fallback.AppBarBackground),
                NormalizeToken(tokens.AppBarText, fallback.AppBarText),
                NormalizeToken(tokens.DrawerBackground, fallback.DrawerBackground),
                NormalizeToken(tokens.DrawerText, fallback.DrawerText),
                NormalizeToken(tokens.ButtonText, fallback.ButtonText),
                NormalizeToken(tokens.DisabledBackground, fallback.DisabledBackground),
                NormalizeToken(tokens.DisabledText, fallback.DisabledText),
                NormalizeToken(tokens.DisabledBorder, fallback.DisabledBorder),
                NormalizeToken(tokens.InputBackground, fallback.InputBackground),
                NormalizeToken(tokens.InputBorder, fallback.InputBorder))
        };
    }

    private static string NormalizeToken(string? value, string fallback)
    {
        return string.IsNullOrWhiteSpace(value) ? fallback : value.Trim();
    }

    public static string GetTokenValue(ColorSchemeTokens tokens, string tokenName)
    {
        return tokenName switch
        {
            nameof(ColorSchemeTokens.Background) => tokens.Background,
            nameof(ColorSchemeTokens.CardBackground) => tokens.CardBackground,
            nameof(ColorSchemeTokens.CardBorder) => tokens.CardBorder,
            nameof(ColorSchemeTokens.Ink) => tokens.Ink,
            nameof(ColorSchemeTokens.Muted) => tokens.Muted,
            nameof(ColorSchemeTokens.Primary) => tokens.Primary,
            nameof(ColorSchemeTokens.Accent) => tokens.Accent,
            nameof(ColorSchemeTokens.Danger) => tokens.Danger,
            nameof(ColorSchemeTokens.Success) => tokens.Success,
            nameof(ColorSchemeTokens.Focus) => tokens.Focus,
            nameof(ColorSchemeTokens.Shadow) => tokens.Shadow,
            nameof(ColorSchemeTokens.Surface) => tokens.Surface,
            nameof(ColorSchemeTokens.SurfaceStrong) => tokens.SurfaceStrong,
            nameof(ColorSchemeTokens.ChartPrimary) => tokens.ChartPrimary,
            nameof(ColorSchemeTokens.ChartSecondary) => tokens.ChartSecondary,
            nameof(ColorSchemeTokens.TaskNegative) => tokens.TaskNegative,
            nameof(ColorSchemeTokens.TaskNeutral) => tokens.TaskNeutral,
            nameof(ColorSchemeTokens.TaskPositive) => tokens.TaskPositive,
            nameof(ColorSchemeTokens.AppBarBackground) => tokens.AppBarBackground,
            nameof(ColorSchemeTokens.AppBarText) => tokens.AppBarText,
            nameof(ColorSchemeTokens.DrawerBackground) => tokens.DrawerBackground,
            nameof(ColorSchemeTokens.DrawerText) => tokens.DrawerText,
            nameof(ColorSchemeTokens.ButtonText) => tokens.ButtonText,
            nameof(ColorSchemeTokens.DisabledBackground) => tokens.DisabledBackground,
            nameof(ColorSchemeTokens.DisabledText) => tokens.DisabledText,
            nameof(ColorSchemeTokens.DisabledBorder) => tokens.DisabledBorder,
            nameof(ColorSchemeTokens.InputBackground) => tokens.InputBackground,
            nameof(ColorSchemeTokens.InputBorder) => tokens.InputBorder,
            _ => string.Empty
        };
    }

    public static ColorSchemeTokens WithTokenValue(ColorSchemeTokens tokens, string tokenName, string value)
    {
        return tokenName switch
        {
            nameof(ColorSchemeTokens.Background) => tokens with { Background = value },
            nameof(ColorSchemeTokens.CardBackground) => tokens with { CardBackground = value },
            nameof(ColorSchemeTokens.CardBorder) => tokens with { CardBorder = value },
            nameof(ColorSchemeTokens.Ink) => tokens with { Ink = value },
            nameof(ColorSchemeTokens.Muted) => tokens with { Muted = value },
            nameof(ColorSchemeTokens.Primary) => tokens with { Primary = value },
            nameof(ColorSchemeTokens.Accent) => tokens with { Accent = value },
            nameof(ColorSchemeTokens.Danger) => tokens with { Danger = value },
            nameof(ColorSchemeTokens.Success) => tokens with { Success = value },
            nameof(ColorSchemeTokens.Focus) => tokens with { Focus = value },
            nameof(ColorSchemeTokens.Shadow) => tokens with { Shadow = value },
            nameof(ColorSchemeTokens.Surface) => tokens with { Surface = value },
            nameof(ColorSchemeTokens.SurfaceStrong) => tokens with { SurfaceStrong = value },
            nameof(ColorSchemeTokens.ChartPrimary) => tokens with { ChartPrimary = value },
            nameof(ColorSchemeTokens.ChartSecondary) => tokens with { ChartSecondary = value },
            nameof(ColorSchemeTokens.TaskNegative) => tokens with { TaskNegative = value },
            nameof(ColorSchemeTokens.TaskNeutral) => tokens with { TaskNeutral = value },
            nameof(ColorSchemeTokens.TaskPositive) => tokens with { TaskPositive = value },
            nameof(ColorSchemeTokens.AppBarBackground) => tokens with { AppBarBackground = value },
            nameof(ColorSchemeTokens.AppBarText) => tokens with { AppBarText = value },
            nameof(ColorSchemeTokens.DrawerBackground) => tokens with { DrawerBackground = value },
            nameof(ColorSchemeTokens.DrawerText) => tokens with { DrawerText = value },
            nameof(ColorSchemeTokens.ButtonText) => tokens with { ButtonText = value },
            nameof(ColorSchemeTokens.DisabledBackground) => tokens with { DisabledBackground = value },
            nameof(ColorSchemeTokens.DisabledText) => tokens with { DisabledText = value },
            nameof(ColorSchemeTokens.DisabledBorder) => tokens with { DisabledBorder = value },
            nameof(ColorSchemeTokens.InputBackground) => tokens with { InputBackground = value },
            nameof(ColorSchemeTokens.InputBorder) => tokens with { InputBorder = value },
            _ => tokens
        };
    }

    public static IReadOnlyList<string> Validate(ColorSchemeDefinition scheme)
    {
        scheme = Complete(scheme);
        var errors = new List<string>();
        if (string.IsNullOrWhiteSpace(scheme.Name))
        {
            errors.Add("Scheme name is required.");
        }

        foreach (var token in EditableTokens)
        {
            if (!IsValidTokenValue(GetTokenValue(scheme.Tokens, token.Name)))
            {
                errors.Add($"{token.Label} is not a supported color value.");
            }
        }

        return errors;
    }

    [GeneratedRegex("""^(#[0-9a-fA-F]{3,8}|rgba?\([^)]+\)|hsla?\([^)]+\)|color-mix\([^)]+\)|[a-zA-Z]+|(?:-?\d+(?:\.\d+)?(?:px|rem|em)?\s+){2,6}(?:#[0-9a-fA-F]{3,8}|rgba?\([^)]+\)|[a-zA-Z]+))$""", RegexOptions.CultureInvariant)]
    private static partial Regex CssColorOrShadowPattern();
}

public sealed record ColorSchemeDefinition(
    string Id,
    string Name,
    bool IsBuiltIn,
    ColorSchemeTokens Tokens);

public sealed record ColorSchemeTokens(
    string Background,
    string CardBackground,
    string CardBorder,
    string Ink,
    string Muted,
    string Primary,
    string Accent,
    string Danger,
    string Success,
    string Focus,
    string Shadow,
    string Surface,
    string SurfaceStrong,
    string ChartPrimary,
    string ChartSecondary,
    string TaskNegative,
    string TaskNeutral,
    string TaskPositive,
    string AppBarBackground,
    string AppBarText,
    string DrawerBackground,
    string DrawerText,
    string ButtonText,
    string DisabledBackground,
    string DisabledText,
    string DisabledBorder,
    string InputBackground,
    string InputBorder);

public sealed record ColorSchemeTokenDescriptor(string Name, string Label);

public sealed record ColorSchemePreferences(
    string SelectedSchemeId,
    IReadOnlyList<ColorSchemeDefinition> CustomSchemes);

public sealed record ColorSchemeState(
    ColorSchemeDefinition ActiveScheme,
    IReadOnlyList<ColorSchemeDefinition> BuiltInSchemes,
    IReadOnlyList<ColorSchemeDefinition> CustomSchemes);
